### ISSUE TITLE
Would you be interested in giving up the npm package name for this?

### ISSUE THREAD

**Issue by corysimmons** [perfectworks/lost#1]
I have a grid system I'd like to use it for https://github.com/corysimmons/lost

If not, no biggie, just figured I'd ask. Thanks

**Comment by perfectworks** [comment]
Just deleted my package, happy hacking!

Regards,
Ethan Zhang

--
晓来雨过 遗踪何在 一池萍碎 春色三分 两分尘土 一分流水
perfectworks@gmail.com

**Comment by corysimmons** [comment]
Thank you
